### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by theindiepocalypse** [comment]
@skariel:

Thanks for opening this pull request!

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:







this pull request is closed, please reopen to merge

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:







merged!
The new ownership structure:

Owner | Percent
-------|---------
@theindiepocalypse|5
@skariel|95
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:







this pull request is closed, please reopen to merge

**Pull request merged**
