### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse request 0.5

**Comment by skariel** [comment]
@theindiepocalypse list commands

**Comment by theindiepocalypse** [comment]
@skariel: the commands are listed in the following examples:
change policy issue 30
open
close
delete repo
request 0.3
merge
list owners
offer 0.3
show creator
list admins
list commands
negotiation status
hi
show policy

**Comment by skariel** [comment]
@theindiepocalypse neogtiation status

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by skariel** [comment]
th

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by theindiepocalypse** [comment]
@skariel: cannot determine mergeability of pull request. Please try again later

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by theindiepocalypse** [comment]
@skariel: cannot determine mergeability of pull request. Please try again later

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: Cannot merge right now. Maybe our DB is not yet in sync with Github. Please try again later...

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: merged!
The new ownership structure:



Owner | Percent
-------|---------
@theindiepocalypse|5.0000
@skariel|95.0000
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: this pull request is already merged!

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by theindiepocalypse** [comment]
@skariel: this pull request is already merged, cannot place a request for merge

**Pull request merged**
