### PR TITLE
adding kkkks

### PR DESCRIPTION
**Pull request by crazyduck2**

### CODE REVIEW

**Comment by crazyduck2** [comment]
@list owners

**Comment by crazyduck2** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@crazyduck2: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|0.00
@skariel|0.00
*total* | 100.0

**Comment by crazyduck2** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@crazyduck2: Only owners with more than 50.00% ownership can close issues. You currently have 0.00%

**Comment by crazyduck2** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@crazyduck2: hi!

**Comment by crazyduck2** [comment]
@theindiepocalypse close

**Comment by crazyduck2** [comment]
@theindiepocalypse open

**Comment by crazyduck2** [comment]
@theindiepocalypse close

**Pull request closed without merging**
