### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: merged!
The new ownership structure:



Owner | Percent
-------|---------
@theindiepocalypse|5.0000
@skariel|95.0000
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse close

**Comment by skariel** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@skariel: this pull request is already closed

**Comment by skariel** [comment]
@theindiepocalypse open

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse open

**Pull request merged**
