### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**
@theindiepocalypse request 3.1

### CODE REVIEW

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 3.1%

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 3.1000%
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse list commands

**Comment by theindiepocalypse** [comment]
@skariel: the commands are listed in the following examples:
list owners
open
offer 0.3
hi
show policy
close
list admins
change policy issue 30
list commands
delete repo
negotiation status
show creator
merge
request 0.3

**Comment by skariel** [comment]
@theindiepocalypse close issue

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse close

**Pull request closed without merging**
