### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 50.00
minimal ownership for changing policy is 50.00

**Comment by skariel** [comment]
@theindiepocalypse change issue policy 0.1

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list command

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list commands

**Comment by theindiepocalypse** [comment]
@skariel: the commands are listed in the following examples:
change policy policy 30%
offer 0.3%
delete repo
hi
open
show creator
negotiation status
show policy
list commands
change policy issue 30%
close
list admins
change policy merging 30%
merge
list owners
request 0.3%

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 0.1

**Comment by theindiepocalypse** [comment]
@skariel: the ownership to manage isues must be above 1%

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 3%

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 50.00
minimal ownership for changing policy is 50.00

**Comment by skariel** [comment]
change policy issue 30%

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 30%

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 30

**Comment by theindiepocalypse** [comment]
@skariel: policy changed

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 3%

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 3%

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 30.00
minimal ownership for changing policy is 50.00

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 7

**Comment by theindiepocalypse** [comment]
@skariel: policy changed

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 8%

**Comment by skariel** [comment]
@theindiepocalypse change policy issue 1.2%

**Comment by theindiepocalypse** [comment]
@skariel: policy changed

**Comment by skariel** [comment]
@theindiepocalypse show policies

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 1.20
minimal ownership for changing policy is 50.00

**Comment by skariel** [comment]
@theindiepocalypse offer 4.5%

**Comment by theindiepocalypse** [comment]
@skariel: only users not creating the pull request can make an offer for merge

**Comment by skariel** [comment]
@theindiepocalypse request 4.5%

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 4.5%%

**Comment by skariel** [comment]
@theindiepocalypse negotiations status

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 4.50%
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 1.20
minimal ownership for changing policy is 50.00

**Comment by skariel** [comment]
@theindiepocalypse show policy

**Comment by theindiepocalypse** [comment]
@skariel: minimal ownership for manaing issues is 1.20
minimal ownership for changing policy is 50.00
merging consesus chived with at least 50.00% ownership

**Comment by crazyduck2** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@crazyduck2: Only owners with more than 1.20% ownership can close issues. You currently have no ownership at all...

**Comment by crazyduck2** [comment]
@theindiepocalypse list commands

**Comment by theindiepocalypse** [comment]
@crazyduck2: the commands are listed in the following examples:
delete repo
open
change policy issue 30%
change policy merging 30%
list owners
hi
request 0.3%
change policy policy 30%
close
list commands
show policy
show creator
merge
list admins
offer 0.3%
negotiation status

**Comment by crazyduck2** [comment]
@theindiepocalypse show creator

**Comment by theindiepocalypse** [comment]
@crazyduck2: the creator of this repo is @skariel

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse offer 3%

**Comment by theindiepocalypse** [comment]
@skariel: only users not creating the pull request can make an offer for merge

**Comment by skariel** [comment]
@theindiepocalypse request 3%

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 3%%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse close

**Pull request closed without merging**
