### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by theindiepocalypse** [comment]
@skariel:

Thanks for opening this pull request!

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:







this pull request is already merged!

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:







this pull request is not mergeable automatically (the merge button) maybe a rebase will solve the issue? I can only merge with the merge button...

**Comment by skariel** [comment]
1233

**Comment by skariel** [comment]
@theindiepocalypse say hi

**Comment by theindiepocalypse** [comment]
@skariel:





hi!

**Comment by skariel** [comment]
#Cool!

**Pull request closed without merging**
