### PR TITLE
some stuff in readme

### PR DESCRIPTION
**Pull request by crazyduck2**

### CODE REVIEW

**Comment by crazyduck2** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@crazyduck2: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|5.00
@skariel|95.00
*total* | 100.0

**Comment by crazyduck2** [comment]
@theindiepocalypse request 7%

**Comment by theindiepocalypse** [comment]
@crazyduck2: request for merge created as 7%%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 7%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse mrge

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: cannot find the request. Please try again later, or contact an admin

**Comment by skariel** [comment]
@theindiepocalypse negotiations status

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 7.00%


Owner | Current offer
-------|---------
@skariel|7.00
*total* | 7.00

**Comment by skariel** [comment]
@theindiepocalypse offer 3%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 3%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 7.00%
required for acceptance: 3.00%
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 7.00%


Owner | Current offer
-------|---------
@skariel|3.00
*total* | 3.00

**Comment by skariel** [comment]
@theindiepocalypse offer 4%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 4%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 7.00%
required for acceptance: 4.00%
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 9%

**Comment by skariel** [comment]
@theindiepocalypse list ownership

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|5.00
@skariel|95.00
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 7.00%


Owner | Current offer
-------|---------
@skariel|9.00
*total* | 9.00

**Comment by skariel** [comment]
@theindiepocalypse offer 2%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 2%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 7.00%
required for acceptance: 2.00%
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 7%

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|5.00
@skariel|95.00
*total* | 100.0

**Pull request merged**
