### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by crazyduck2**

### CODE REVIEW

**Comment by crazyduck2** [comment]
@theindiepocalypse list commands

**Comment by theindiepocalypse** [comment]
@crazyduck2: the commands are listed in the following examples:
delete repo
open
change policy issue 30%
change policy merging 30%
list owners
hi
request 0.3%
change policy policy 30%
close
list commands
show policy
show creator
merge
list admins
offer 0.3%
negotiation status

**Comment by crazyduck2** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@crazyduck2: no requested percentage for merging yet
thre are no offers

**Comment by crazyduck2** [comment]
@theindiepocalypse offer 5%

**Comment by theindiepocalypse** [comment]
@crazyduck2: only users not creating the pull request can make an offer for merge

**Comment by crazyduck2** [comment]
@theindiepocalypse request 3%

**Comment by theindiepocalypse** [comment]
@crazyduck2: request for merge created as 3%%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 1.1%

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 1.1%%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: no request was made yet
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 3.00%


Owner | Current offer
-------|---------
@skariel|1.10
*total* | 0.0

**Comment by skariel** [comment]
@theindiepocalypse offer 0.9%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 0.9%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.00%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 0.99%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 0.99%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.00%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 0.2%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 0.2%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.00%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 0.13%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 0.13%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.00%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 0.17%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 0.17%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.00%
required for acceptance: 0.17%
is negotiation succesful? not yet

**Comment by skariel** [comment]
@theindiepocalypse offer 7%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge updated to 7%
nego status:

ownership currently accepted: 95.00%
users currently accepted: @skariel
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.00%
required for acceptance: 7.00%
is negotiation succesful? yes!

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse offer1.2%

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse offer 1.2%

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet


Owner | Current offer
-------|---------
@skariel|1.20
*total* | 1.20

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@theindiepocalypse|5.00
@skariel|95.00
*total* | 100.0

**Comment by crazyduck2** [comment]
@theindiepocalypse request 0.5%

**Comment by crazyduck2** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@crazyduck2: requested for merge 0.50%


Owner | Current offer
-------|---------
@skariel|1.20
*total* | 1.20

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse offer 5%

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet


Owner | Current offer
-------|---------
@skariel|5.00
*total* | 5.00

**Comment by skariel** [comment]
@theindiepocalypse offer 7.1%

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@theindiepocalypse|5.00
@skariel|95.00
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: no requested percentage for merging yet


Owner | Current offer
-------|---------
@skariel|7.10
*total* | 7.10

**Comment by skariel** [comment]
@theindiepocalypse offer 3.1%

**Comment by skariel** [comment]
@theindiepocalypse offer 3.3%

**Comment by skariel** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@skariel: hi!

**Comment by skariel** [comment]
@theindiepocalypse offer 7.7%

**Comment by skariel** [comment]
@theindiepocalypse close

**Pull request closed without merging**
