### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse request 0.9

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 0.9%

**Comment by skariel** [comment]
@theindiepocalypse request 1.1

**Comment by theindiepocalypse** [comment]
@skariel: request for merge updated to 1.1%

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: merged!
The new ownership structure:



Owner | Percent
-------|---------
@theindiepocalypse|5.0000
@skariel|95.0000
*total* | 100.0

**Pull request merged**
