### PR TITLE
adding js

### PR DESCRIPTION
**Pull request by crazyduck2**

### CODE REVIEW

**Comment by crazyduck2** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@crazyduck2: no requested percentage for merging yet
thre are no offers

**Comment by crazyduck2** [comment]
@theindiepocalypse request 3.4%

**Comment by theindiepocalypse** [comment]
@crazyduck2: request for merge created as 3.4%%
nego status:

ownership currently accepted: 0.0%
users currently accepted: none
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.4%
required for acceptance: not even for free ;)
is negotiation succesful? not yet

**Comment by crazyduck2** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@crazyduck2: requested for merge 3.40%
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse offer 3.4%

**Comment by theindiepocalypse** [comment]
@skariel: Only owners with ownership can make offers

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|0.00
@skariel|0.00
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|0.00
@skariel|0.00
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse list owners

**Comment by theindiepocalypse** [comment]
@skariel: 

Owner | Percent
-------|---------
@crazyduck2|0.00
@theindiepocalypse|5.00
@skariel|95.00
*total* | 100.0

**Comment by skariel** [comment]
@theindiepocalypse offer 3.4%

**Comment by theindiepocalypse** [comment]
@skariel: offer for merge created as 3.4%
nego status:

ownership currently accepted: 95.00%
users currently accepted: @skariel
required ownership for merge, per policy: 50.00%
requested ownership to merge: 3.40%
required for acceptance: 3.40%
is negotiation succesful? yes!

negotiation succesful. Merging

merged!
The new ownership structure:



Owner | Percent
-------|---------
@crazyduck2|3.40
@theindiepocalypse|4.83
@skariel|91.77
*total* | 100.0

**Pull request merged**
