### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by theindiepocalypse** [comment]
@skariel: cannot determine mergeability of pull request. Please try again later

**Comment by skariel** [comment]
@theindiepocalypse request 0.3

**Comment by theindiepocalypse** [comment]
@skariel: request for merge created as 0.3%

**Comment by skariel** [comment]
@theindiepocalypse  negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse offer 0.2

**Comment by theindiepocalypse** [comment]
@skariel: only users not creating the pull request can make an offer for merge

**Comment by skariel** [comment]
@theindiepocalypse negotiation status

**Comment by theindiepocalypse** [comment]
@skariel: requested for merge 0.3000%
thre are no offers

**Comment by skariel** [comment]
@theindiepocalypse request 0.7

**Comment by theindiepocalypse** [comment]
@skariel: cannot determine mergeability of pull request. Please try again later

**Comment by skariel** [comment]
@theindiepocalypse request 0.7

**Comment by theindiepocalypse** [comment]
@skariel: request for merge updated to 0.7%

**Comment by skariel** [comment]
@req

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel: merged!
The new ownership structure:



Owner | Percent
-------|---------
@theindiepocalypse|5.0000
@skariel|95.0000
*total* | 100.0

**Pull request merged**
