### PR TITLE
updating readme

### PR DESCRIPTION
**Pull request by skariel**

### CODE REVIEW

**Comment by theindiepocalypse** [comment]
@skariel:

Thanks for opening this pull request!

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:

Thanks for commenting on this pull request





merging commands are allowed only on pull requests, nothing to merge here :)

**Comment by skariel** [comment]
@theindiepocalypse merge

**Comment by theindiepocalypse** [comment]
@skariel:

Thanks for commenting on this pull request





merged!
The new ownership structure:

**Pull request merged**
